export const ADD_MAINCATEGORY="ADDMAINCATEGORY"
export const ADD_MAINCATEGORY_RED="ADDMAINCATEGORYRED"
export const GET_MAINCATEGORY="GETMAINCATEGORY"
export const GET_MAINCATEGORY_RED="GETMAINCATEGORYRED"
export const UPDATE_MAINCATEGORY="UPDATEMAINCATEGORY"
export const UPDATE_MAINCATEGORY_RED="GETMAINCATEGORYRED"
export const DELETE_MAINCATEGORY="DELETEMAINCATEGORY"
export const DELETE_MAINCATEGORY_RED = "GETMAINCATEGORYRED"

// FOR SUBCATEGORY

export const ADD_SUBCATEGORY="ADDSUBCATEGORY"
export const ADD_SUBCATEGORY_RED="ADDSUBCATEGORYRED"
export const GET_SUBCATEGORY="GETSUBCATEGORY"
export const GET_SUBCATEGORY_RED="GETSUBCATEGORYRED"
export const UPDATE_SUBCATEGORY="UPDATESUBCATEGORY"
export const UPDATE_SUBCATEGORY_RED="GETSUBCATEGORYRED"
export const DELETE_SUBCATEGORY="DELETESUBCATEGORY"
export const DELETE_SUBCATEGORY_RED = "GETSUBCATEGORYRED"

// BRANDS

export const ADD_BRAND="ADDBRAND"
export const ADD_BRAND_RED="ADDBRANDRED"
export const GET_BRAND="GETBRAND"
export const GET_BRAND_RED="GETBRANDRED"
export const UPDATE_BRAND="UPDATEBRAND"
export const UPDATE_BRAND_RED="GETBRANDRED"
export const DELETE_BRAND="DELETEBRAND"
export const DELETE_BRAND_RED = "GETBRANDRED"

// PRODUCTS

export const ADD_PRODUCT="ADDPRODUCT"
export const ADD_PRODUCT_RED="ADDPRODUCTRED"
export const GET_PRODUCT="GETPRODUCT"
export const GET_PRODUCT_RED="GETPRODUCTRED"
export const UPDATE_PRODUCT="UPDATEPRODUCT"
export const UPDATE_PRODUCT_RED="GETPRODUCTRED"
export const DELETE_PRODUCT="DELETEPRODUCT"
export const DELETE_PRODUCT_RED = "GETPRODUCTRED"