export const ADD_MAINCATEGORY="ADDMAINCATEGORY"
export const ADD_MAINCATEGORY_RED="ADDMAINCATEGORYRED"
export const GET_MAINCATEGORY="GETMAINCATEGORY"
export const GET_MAINCATEGORY_RED="GETMAINCATEGORYRED"
export const UPDATE_MAINCATEGORY="UPDATEMAINCATEGORY"
export const UPDATE_MAINCATEGORY_RED="GETMAINCATEGORYRED"
export const DELETE_MAINCATEGORY="DELETEMAINCATEGORY"
export const DELETE_MAINCATEGORY_RED = "GETMAINCATEGORYRED"

// FOR SUBCATEGORY

export const ADD_SUBCATEGORY="ADDSUBCATEGORY"
export const ADD_SUBCATEGORY_RED="ADDSUBCATEGORYRED"
export const GET_SUBCATEGORY="GETSUBCATEGORY"
export const GET_SUBCATEGORY_RED="GETSUBCATEGORYRED"
export const UPDATE_SUBCATEGORY="UPDATESUBCATEGORY"
export const UPDATE_SUBCATEGORY_RED="GETSUBCATEGORYRED"
export const DELETE_SUBCATEGORY="DELETESUBCATEGORY"
export const DELETE_SUBCATEGORY_RED = "GETSUBCATEGORYRED"

// BRANDS

export const ADD_BRAND="ADDBRAND"
export const ADD_BRAND_RED="ADDBRANDRED"
export const GET_BRAND="GETBRAND"
export const GET_BRAND_RED="GETBRANDRED"
export const UPDATE_BRAND="UPDATEBRAND"
export const UPDATE_BRAND_RED="GETBRANDRED"
export const DELETE_BRAND="DELETEBRAND"
export const DELETE_BRAND_RED = "GETBRANDRED"

// PRODUCTS

export const ADD_PRODUCT="ADDPRODUCT"
export const ADD_PRODUCT_RED="ADDPRODUCTRED"
export const GET_PRODUCT="GETPRODUCT"
export const GET_PRODUCT_RED="GETPRODUCTRED"
export const UPDATE_PRODUCT="UPDATEPRODUCT"
export const UPDATE_PRODUCT_RED="GETPRODUCTRED"
export const DELETE_PRODUCT="DELETEPRODUCT"
export const DELETE_PRODUCT_RED = "GETPRODUCTRED"

// USERS

export const ADD_USER="ADDUSER"
export const ADD_USER_RED="ADDUSERRED"
export const GET_USER="GETUSER"
export const GET_USER_RED="GETUSERRED"
export const UPDATE_USER="UPDATEUSER"
export const UPDATE_USER_RED="GETUSERRED"
export const DELETE_USER="DELETEUSER"
export const DELETE_USER_RED = "GETUSERRED"

// CARTS

export const ADD_CART="ADDCART"
export const ADD_CART_RED="ADDCARTRED"
export const GET_CART="GETCART"
export const GET_CART_RED="GETCARTRED"
export const UPDATE_CART="UPDATECART"
export const UPDATE_CART_RED="GETCARTRED"
export const DELETE_CART="DELETECART"
export const DELETE_CART_RED = "GETCARTRED"

// WISHLISTS

export const ADD_WISHLIST="ADDWISHLIST"
export const ADD_WISHLIST_RED="ADDWISHLISTRED"
export const GET_WISHLIST="GETWISHLIST"
export const GET_WISHLIST_RED="GETWISHLISTRED"
export const UPDATE_WISHLIST="UPDATEWISHLIST"
export const UPDATE_WISHLIST_RED="GETWISHLISTRED"
export const DELETE_WISHLIST="DELETEWISHLIST"
export const DELETE_WISHLIST_RED = "GETWISHLISTRED"

// Checkout

export const ADD_CHECKOUT="ADDCHECKOUT"
export const ADD_CHECKOUT_RED="ADDCHECKOUTRED"
export const GET_CHECKOUT="GETCHECKOUT"
export const GET_CHECKOUT_RED="GETCHECKOUTRED"
export const UPDATE_CHECKOUT="UPDATECHECKOUT"
export const UPDATE_CHECKOUT_RED="GETCHECKOUTRED"
export const DELETE_CHECKOUT="DELETECHECKOUT"
export const DELETE_CHECKOUT_RED = "GETCHECKOUTRED"

// Contact

export const ADD_CONTACT="ADDCONTACT"
export const ADD_CONTACT_RED="ADDCONTACTRED"
export const GET_CONTACT="GETCONTACT"
export const GET_CONTACT_RED="GETCONTACTRED"
export const UPDATE_CONTACT="UPDATECONTACT"
export const UPDATE_CONTACT_RED="GETCONTACTRED"
export const DELETE_CONTACT="DELETECONTACT"
export const DELETE_CONTACT_RED = "GETCONTACTRED"

// newsletter

export const ADD_NEWSLETTER="ADDNEWSLETTER"
export const ADD_NEWSLETTER_RED="ADDNEWSLETTERRED"
export const GET_NEWSLETTER="GETNEWSLETTER"
export const GET_NEWSLETTER_RED="GETNEWSLETTERRED"
export const UPDATE_NEWSLETTER="UPDATENEWSLETTER"
export const UPDATE_NEWSLETTER_RED="GETNEWSLETTERRED"
export const DELETE_NEWSLETTER="DELETENEWSLETTER"
export const DELETE_NEWSLETTER_RED = "GETNEWSLETTERRED"